### PR TITLE
Add callback method when diagram has updated

### PR DESCRIPTION
**Pull request by Yahkob**
Thought other people may think this is useful essentially added a method that will fire when all venn tweens have completed when the diagram is updated. This is helpful if you need logic to fire when the whole diagram is rendered. Used @mbostock 's code from this [thread] (https://groups.google.com/d/msg/d3-js/WC_7Xi6VV50/j1HK0vIWI-EJ) to ensure callback only fires on the last updated items tween

### CODE REVIEW

**Comment by benfred** [comment]
Thanks for the PR!

I'm wondering though if this is necessary. 

The enter/update/exit values are already returned, so you can do things like add extra elements that transition smoothly with the diagram (for instance add an extra label like here: http://benfred.github.io/venn.js/examples/sublabels.html). It seems like you could just add your callback on the returned 'exit' value in a similar way?

**Comment by Yahkob** [comment]
@benfred as far as I know from hacking around and reading D3 docs; if you add a call back on the exit value (something like `exit.call(someCallback)` ) DOM values returned from methods like `getBBox` or `getClientBoundingRect` will not be correct. The reason (to my understanding) here you cant just use exit's callback is that the tweens will not have completed animating and the values of DOM elements will be incorrect at that point. I could be wrong but this is the only way I have been able to fire a callback at the point tweens are finished animating. The logic in my code relies on having the post-tween values of elements.

**Comment by benfred** [comment]
Err - yeah, I meant to say the 'update' member instead of exit =(

I hacked up a little example to show what I mean  - it draws a bounding box over each circle and does '.each("end", function() {...})' after each time they : move: http://benfred.github.io/venn.js/examples/boundingbox.html

I think by overriding the function there you can get what you want?

**Comment by Yahkob** [comment]
Yep, this is essentially what I'm doing in my pull request. The only difference is that I am incrementing to keep track of how many elements have completed their tween so that the callback only fires when every tween is complete. Might be a very small use case for people other than me but thought I'd open the PR regardless :)

**Comment by Yahkob** [comment]
I'll close for now if you're interested in moving forward at some point lets reopen this

**Pull request closed without merging**
