### PR TITLE
Es6

### PR DESCRIPTION
**Pull request by christophe-g**
Hey, 
I am aware this PR is quite something to bite !

Basically, it is a refactoring to comply with ES6 import/export statements. It is also in line with http://bost.ocks.org/mike/d3-plugin/. Nothing substantial is done on the core stuff.

The build can now be run just with `npm install` 

Cheers, 
C.

### CODE REVIEW

**Comment by christophe-g** [comment]
It appears git is not reconciling my changes with the master code base - seems there is some issue with spaces...

I'll try to propose a cleaner PR - this one seems a bit ugly !

**Comment by benfred** [comment]
awesome! I read the d3-plugin post when it came out and am totally on board with the idea of transitioning over to this style.

I'm travelling right now - and won't be able to review any code until the weekend though.

**Comment by christophe-g** [comment]
Cool, thanks for the reply,

Tried to play around with space indent and beautifyer to try submit a cleaner PR, without success ... 

Otherwise, feel free to have a look at https://github.com/christophe-g/d3-venn to see an extension of your work.
Happy travel and cheers, 
C.

**Comment by benfred** [comment]
So - there was a minor issue here that prevented me from merging. 

The unittests weren't running because of some missing exports, I fixed those and switched to faucet/tape for them at the same time here: https://github.com/benfred/venn.js/commit/5cec061f84fea530dac748b58979cea9b378b5b3 Also travisCI was complaining about something on this PR that I wasn't sure about.

Your d3-venn project looks nice! good work

**Pull request closed without merging**
