### PR TITLE
add opt-in support for viewBox

### LINKED ISSUE #97: Responsiveness
I want the chart to auto adjust to width.

screen shot 2017-07-26 at 7 34 18 pm

My code

```
var sets = [{
                        sets: ['Present'],
                        size: xx
                        
                    },
                    {
                        sets: ['Holiday'],
                        size: xx
                        
                    },
                    {
                        sets: ['WeeklyOff'],
                        size: xx
                        
                    },
                    {
                        sets: ['Present','Holiday'],
                        size: xx
                        
                    },
                    {
                        sets: ['Present','WeeklyOff'],
                        size: XX
                        
                    },
                    {
                        sets: ['WeeklyOff','Holiday'],
                        size: xx
                        
                    },
                    {
                        sets: ['WeeklyOff','Holiday','Present'],
                        size: XX
                        
                    }
                ];

                var chart = venn.VennDiagram(); 
              d3.select("#venn").datum(sets).call(chart);
```

### PR DESCRIPTION
**Pull request by davidjgoss**
Fixes #97 

Add support, without changing the default behaviour, to apply the width and height to the SVG via the [`viewBox` attribute](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox) rather than `width` and `height` attributes. This is preferable when incorporating into responsive layouts, as it specifies the width and height merely as an aspect ratio and lets the SVG grow or shrink to any size depending on its containing element (and/or any CSS applied).

To use, you just call `useViewBox` on the created `VennDiagram` - it's a one-way setting:

```javascript
var chart = venn.VennDiagram();
chart.useViewBox();
// draw with data
```

I added an alternate version of the "simple" example which uses this, and added screenshot tests for both with BackstopJS (sorry about all the boilerplate files!) which show the difference - you can run `npm run backstop-check` to see them.

### CODE REVIEW

**Comment by clintonmedbery** [comment]
@benfred ^

**Comment by clintonmedbery** [comment]
@davidjgoss is there a way to set min or max height/width with this? Thanks btw!

**Comment by davidjgoss** [comment]
@clintonmedbery no, this just covers viewBox. For min/max height I would probably do that with .style (https://github.com/d3/d3-selection/blob/master/README.md#modifying-elements) or CSS

**Comment by JelleBlaauw** [comment]
Is this going to be merged anytime soon?

**Pull request closed without merging**
